// AUTO-GENERATED by scripts/gen_col_indices.py — DO NOT EDIT MANUALLY
// Regenerate: python3 scripts/gen_col_indices.py
// Source of truth: src/dsdgen/dsdgen_wrapper.cpp (get_schema() switch)
//
// Provides zero-overhead named column indices for BuilderMap (vector) access.
// Usage: builders[col::store_returns::sr_returned_date_sk]
#pragma once
#include <cstddef>

namespace tpcds {
namespace col {

// call_center (31 columns)
namespace call_center {
    constexpr std::size_t cc_call_center_sk = 0;
    constexpr std::size_t cc_call_center_id = 1;
    constexpr std::size_t cc_rec_start_date_sk = 2;
    constexpr std::size_t cc_rec_end_date_sk = 3;
    constexpr std::size_t cc_closed_date_sk = 4;
    constexpr std::size_t cc_open_date_sk = 5;
    constexpr std::size_t cc_name = 6;
    constexpr std::size_t cc_class = 7;
    constexpr std::size_t cc_employees = 8;
    constexpr std::size_t cc_sq_ft = 9;
    constexpr std::size_t cc_hours = 10;
    constexpr std::size_t cc_manager = 11;
    constexpr std::size_t cc_mkt_id = 12;
    constexpr std::size_t cc_mkt_class = 13;
    constexpr std::size_t cc_mkt_desc = 14;
    constexpr std::size_t cc_market_manager = 15;
    constexpr std::size_t cc_division = 16;
    constexpr std::size_t cc_division_name = 17;
    constexpr std::size_t cc_company = 18;
    constexpr std::size_t cc_company_name = 19;
    constexpr std::size_t cc_street_number = 20;
    constexpr std::size_t cc_street_name = 21;
    constexpr std::size_t cc_street_type = 22;
    constexpr std::size_t cc_suite_number = 23;
    constexpr std::size_t cc_city = 24;
    constexpr std::size_t cc_county = 25;
    constexpr std::size_t cc_state = 26;
    constexpr std::size_t cc_zip = 27;
    constexpr std::size_t cc_country = 28;
    constexpr std::size_t cc_gmt_offset = 29;
    constexpr std::size_t cc_tax_percentage = 30;
}

// catalog_page (9 columns)
namespace catalog_page {
    constexpr std::size_t cp_catalog_page_sk = 0;
    constexpr std::size_t cp_catalog_page_id = 1;
    constexpr std::size_t cp_start_date_sk = 2;
    constexpr std::size_t cp_end_date_sk = 3;
    constexpr std::size_t cp_department = 4;
    constexpr std::size_t cp_catalog_number = 5;
    constexpr std::size_t cp_catalog_page_number = 6;
    constexpr std::size_t cp_description = 7;
    constexpr std::size_t cp_type = 8;
}

// catalog_returns (27 columns)
namespace catalog_returns {
    constexpr std::size_t cr_returned_date_sk = 0;
    constexpr std::size_t cr_returned_time_sk = 1;
    constexpr std::size_t cr_item_sk = 2;
    constexpr std::size_t cr_refunded_customer_sk = 3;
    constexpr std::size_t cr_refunded_cdemo_sk = 4;
    constexpr std::size_t cr_refunded_hdemo_sk = 5;
    constexpr std::size_t cr_refunded_addr_sk = 6;
    constexpr std::size_t cr_returning_customer_sk = 7;
    constexpr std::size_t cr_returning_cdemo_sk = 8;
    constexpr std::size_t cr_returning_hdemo_sk = 9;
    constexpr std::size_t cr_returning_addr_sk = 10;
    constexpr std::size_t cr_call_center_sk = 11;
    constexpr std::size_t cr_catalog_page_sk = 12;
    constexpr std::size_t cr_ship_mode_sk = 13;
    constexpr std::size_t cr_warehouse_sk = 14;
    constexpr std::size_t cr_reason_sk = 15;
    constexpr std::size_t cr_order_number = 16;
    constexpr std::size_t cr_quantity = 17;
    constexpr std::size_t cr_net_paid = 18;
    constexpr std::size_t cr_ext_tax = 19;
    constexpr std::size_t cr_net_paid_inc_tax = 20;
    constexpr std::size_t cr_fee = 21;
    constexpr std::size_t cr_ext_ship_cost = 22;
    constexpr std::size_t cr_refunded_cash = 23;
    constexpr std::size_t cr_reversed_charge = 24;
    constexpr std::size_t cr_store_credit = 25;
    constexpr std::size_t cr_net_loss = 26;
}

// catalog_sales (34 columns)
namespace catalog_sales {
    constexpr std::size_t cs_sold_date_sk = 0;
    constexpr std::size_t cs_sold_time_sk = 1;
    constexpr std::size_t cs_ship_date_sk = 2;
    constexpr std::size_t cs_bill_customer_sk = 3;
    constexpr std::size_t cs_bill_cdemo_sk = 4;
    constexpr std::size_t cs_bill_hdemo_sk = 5;
    constexpr std::size_t cs_bill_addr_sk = 6;
    constexpr std::size_t cs_ship_customer_sk = 7;
    constexpr std::size_t cs_ship_cdemo_sk = 8;
    constexpr std::size_t cs_ship_hdemo_sk = 9;
    constexpr std::size_t cs_ship_addr_sk = 10;
    constexpr std::size_t cs_call_center_sk = 11;
    constexpr std::size_t cs_catalog_page_sk = 12;
    constexpr std::size_t cs_ship_mode_sk = 13;
    constexpr std::size_t cs_warehouse_sk = 14;
    constexpr std::size_t cs_item_sk = 15;
    constexpr std::size_t cs_promo_sk = 16;
    constexpr std::size_t cs_order_number = 17;
    constexpr std::size_t cs_quantity = 18;
    constexpr std::size_t cs_wholesale_cost = 19;
    constexpr std::size_t cs_list_price = 20;
    constexpr std::size_t cs_sales_price = 21;
    constexpr std::size_t cs_ext_discount_amt = 22;
    constexpr std::size_t cs_ext_sales_price = 23;
    constexpr std::size_t cs_ext_wholesale_cost = 24;
    constexpr std::size_t cs_ext_list_price = 25;
    constexpr std::size_t cs_ext_tax = 26;
    constexpr std::size_t cs_coupon_amt = 27;
    constexpr std::size_t cs_ext_ship_cost = 28;
    constexpr std::size_t cs_net_paid = 29;
    constexpr std::size_t cs_net_paid_inc_tax = 30;
    constexpr std::size_t cs_net_paid_inc_ship = 31;
    constexpr std::size_t cs_net_paid_inc_ship_tax = 32;
    constexpr std::size_t cs_net_profit = 33;
}

// customer (18 columns)
namespace customer {
    constexpr std::size_t c_customer_sk = 0;
    constexpr std::size_t c_customer_id = 1;
    constexpr std::size_t c_current_cdemo_sk = 2;
    constexpr std::size_t c_current_hdemo_sk = 3;
    constexpr std::size_t c_current_addr_sk = 4;
    constexpr std::size_t c_first_shipto_date_id = 5;
    constexpr std::size_t c_first_sales_date_id = 6;
    constexpr std::size_t c_salutation = 7;
    constexpr std::size_t c_first_name = 8;
    constexpr std::size_t c_last_name = 9;
    constexpr std::size_t c_preferred_cust_flag = 10;
    constexpr std::size_t c_birth_day = 11;
    constexpr std::size_t c_birth_month = 12;
    constexpr std::size_t c_birth_year = 13;
    constexpr std::size_t c_birth_country = 14;
    constexpr std::size_t c_login = 15;
    constexpr std::size_t c_email_address = 16;
    constexpr std::size_t c_last_review_date = 17;
}

// customer_address (13 columns)
namespace customer_address {
    constexpr std::size_t ca_address_sk = 0;
    constexpr std::size_t ca_address_id = 1;
    constexpr std::size_t ca_street_number = 2;
    constexpr std::size_t ca_street_name = 3;
    constexpr std::size_t ca_street_type = 4;
    constexpr std::size_t ca_suite_number = 5;
    constexpr std::size_t ca_city = 6;
    constexpr std::size_t ca_county = 7;
    constexpr std::size_t ca_state = 8;
    constexpr std::size_t ca_zip = 9;
    constexpr std::size_t ca_country = 10;
    constexpr std::size_t ca_gmt_offset = 11;
    constexpr std::size_t ca_location_type = 12;
}

// customer_demographics (9 columns)
namespace customer_demographics {
    constexpr std::size_t cd_demo_sk = 0;
    constexpr std::size_t cd_gender = 1;
    constexpr std::size_t cd_marital_status = 2;
    constexpr std::size_t cd_education_status = 3;
    constexpr std::size_t cd_purchase_estimate = 4;
    constexpr std::size_t cd_credit_rating = 5;
    constexpr std::size_t cd_dep_count = 6;
    constexpr std::size_t cd_dep_employed_count = 7;
    constexpr std::size_t cd_dep_college_count = 8;
}

// date_dim (26 columns)
namespace date_dim {
    constexpr std::size_t d_date_sk = 0;
    constexpr std::size_t d_date_id = 1;
    constexpr std::size_t d_month_seq = 2;
    constexpr std::size_t d_week_seq = 3;
    constexpr std::size_t d_quarter_seq = 4;
    constexpr std::size_t d_year = 5;
    constexpr std::size_t d_dow = 6;
    constexpr std::size_t d_moy = 7;
    constexpr std::size_t d_dom = 8;
    constexpr std::size_t d_qoy = 9;
    constexpr std::size_t d_fy_year = 10;
    constexpr std::size_t d_fy_quarter_seq = 11;
    constexpr std::size_t d_fy_week_seq = 12;
    constexpr std::size_t d_day_name = 13;
    constexpr std::size_t d_holiday = 14;
    constexpr std::size_t d_weekend = 15;
    constexpr std::size_t d_following_holiday = 16;
    constexpr std::size_t d_first_dom = 17;
    constexpr std::size_t d_last_dom = 18;
    constexpr std::size_t d_same_day_ly = 19;
    constexpr std::size_t d_same_day_lq = 20;
    constexpr std::size_t d_current_day = 21;
    constexpr std::size_t d_current_week = 22;
    constexpr std::size_t d_current_month = 23;
    constexpr std::size_t d_current_quarter = 24;
    constexpr std::size_t d_current_year = 25;
}

// household_demographics (5 columns)
namespace household_demographics {
    constexpr std::size_t hd_demo_sk = 0;
    constexpr std::size_t hd_income_band_sk = 1;
    constexpr std::size_t hd_buy_potential = 2;
    constexpr std::size_t hd_dep_count = 3;
    constexpr std::size_t hd_vehicle_count = 4;
}

// income_band (3 columns)
namespace income_band {
    constexpr std::size_t ib_income_band_id = 0;
    constexpr std::size_t ib_lower_bound = 1;
    constexpr std::size_t ib_upper_bound = 2;
}

// inventory (4 columns)
namespace inventory {
    constexpr std::size_t inv_date_sk = 0;
    constexpr std::size_t inv_item_sk = 1;
    constexpr std::size_t inv_warehouse_sk = 2;
    constexpr std::size_t inv_quantity_on_hand = 3;
}

// item (23 columns)
namespace item {
    constexpr std::size_t i_item_sk = 0;
    constexpr std::size_t i_item_id = 1;
    constexpr std::size_t i_rec_start_date_id = 2;
    constexpr std::size_t i_rec_end_date_id = 3;
    constexpr std::size_t i_item_desc = 4;
    constexpr std::size_t i_current_price = 5;
    constexpr std::size_t i_wholesale_cost = 6;
    constexpr std::size_t i_brand_id = 7;
    constexpr std::size_t i_brand = 8;
    constexpr std::size_t i_class_id = 9;
    constexpr std::size_t i_class = 10;
    constexpr std::size_t i_category_id = 11;
    constexpr std::size_t i_category = 12;
    constexpr std::size_t i_manufact_id = 13;
    constexpr std::size_t i_manufact = 14;
    constexpr std::size_t i_size = 15;
    constexpr std::size_t i_formulation = 16;
    constexpr std::size_t i_color = 17;
    constexpr std::size_t i_units = 18;
    constexpr std::size_t i_container = 19;
    constexpr std::size_t i_manager_id = 20;
    constexpr std::size_t i_product_name = 21;
    constexpr std::size_t i_promo_sk = 22;
}

// promotion (19 columns)
namespace promotion {
    constexpr std::size_t p_promo_sk = 0;
    constexpr std::size_t p_promo_id = 1;
    constexpr std::size_t p_start_date_sk = 2;
    constexpr std::size_t p_end_date_sk = 3;
    constexpr std::size_t p_item_sk = 4;
    constexpr std::size_t p_cost = 5;
    constexpr std::size_t p_response_target = 6;
    constexpr std::size_t p_promo_name = 7;
    constexpr std::size_t p_channel_dmail = 8;
    constexpr std::size_t p_channel_email = 9;
    constexpr std::size_t p_channel_catalog = 10;
    constexpr std::size_t p_channel_tv = 11;
    constexpr std::size_t p_channel_radio = 12;
    constexpr std::size_t p_channel_press = 13;
    constexpr std::size_t p_channel_event = 14;
    constexpr std::size_t p_channel_demo = 15;
    constexpr std::size_t p_channel_details = 16;
    constexpr std::size_t p_purpose = 17;
    constexpr std::size_t p_discount_active = 18;
}

// reason (3 columns)
namespace reason {
    constexpr std::size_t r_reason_sk = 0;
    constexpr std::size_t r_reason_id = 1;
    constexpr std::size_t r_reason_desc = 2;
}

// ship_mode (6 columns)
namespace ship_mode {
    constexpr std::size_t sm_ship_mode_sk = 0;
    constexpr std::size_t sm_ship_mode_id = 1;
    constexpr std::size_t sm_type = 2;
    constexpr std::size_t sm_code = 3;
    constexpr std::size_t sm_carrier = 4;
    constexpr std::size_t sm_contract = 5;
}

// store (29 columns)
namespace store {
    constexpr std::size_t s_store_sk = 0;
    constexpr std::size_t s_store_id = 1;
    constexpr std::size_t s_rec_start_date = 2;
    constexpr std::size_t s_rec_end_date = 3;
    constexpr std::size_t s_closed_date_sk = 4;
    constexpr std::size_t s_store_name = 5;
    constexpr std::size_t s_number_employees = 6;
    constexpr std::size_t s_floor_space = 7;
    constexpr std::size_t s_hours = 8;
    constexpr std::size_t s_manager = 9;
    constexpr std::size_t s_market_id = 10;
    constexpr std::size_t s_geography_class = 11;
    constexpr std::size_t s_market_desc = 12;
    constexpr std::size_t s_market_manager = 13;
    constexpr std::size_t s_division_id = 14;
    constexpr std::size_t s_division_name = 15;
    constexpr std::size_t s_company_id = 16;
    constexpr std::size_t s_company_name = 17;
    constexpr std::size_t s_street_number = 18;
    constexpr std::size_t s_street_name = 19;
    constexpr std::size_t s_street_type = 20;
    constexpr std::size_t s_suite_number = 21;
    constexpr std::size_t s_city = 22;
    constexpr std::size_t s_county = 23;
    constexpr std::size_t s_state = 24;
    constexpr std::size_t s_zip = 25;
    constexpr std::size_t s_country = 26;
    constexpr std::size_t s_gmt_offset = 27;
    constexpr std::size_t s_tax_percentage = 28;
}

// store_returns (20 columns)
namespace store_returns {
    constexpr std::size_t sr_returned_date_sk = 0;
    constexpr std::size_t sr_returned_time_sk = 1;
    constexpr std::size_t sr_item_sk = 2;
    constexpr std::size_t sr_customer_sk = 3;
    constexpr std::size_t sr_cdemo_sk = 4;
    constexpr std::size_t sr_hdemo_sk = 5;
    constexpr std::size_t sr_addr_sk = 6;
    constexpr std::size_t sr_store_sk = 7;
    constexpr std::size_t sr_reason_sk = 8;
    constexpr std::size_t sr_ticket_number = 9;
    constexpr std::size_t sr_quantity = 10;
    constexpr std::size_t sr_net_paid = 11;
    constexpr std::size_t sr_ext_tax = 12;
    constexpr std::size_t sr_net_paid_inc_tax = 13;
    constexpr std::size_t sr_fee = 14;
    constexpr std::size_t sr_ext_ship_cost = 15;
    constexpr std::size_t sr_refunded_cash = 16;
    constexpr std::size_t sr_reversed_charge = 17;
    constexpr std::size_t sr_store_credit = 18;
    constexpr std::size_t sr_net_loss = 19;
}

// store_sales (23 columns)
namespace store_sales {
    constexpr std::size_t ss_sold_date_sk = 0;
    constexpr std::size_t ss_sold_time_sk = 1;
    constexpr std::size_t ss_item_sk = 2;
    constexpr std::size_t ss_customer_sk = 3;
    constexpr std::size_t ss_cdemo_sk = 4;
    constexpr std::size_t ss_hdemo_sk = 5;
    constexpr std::size_t ss_addr_sk = 6;
    constexpr std::size_t ss_store_sk = 7;
    constexpr std::size_t ss_promo_sk = 8;
    constexpr std::size_t ss_ticket_number = 9;
    constexpr std::size_t ss_quantity = 10;
    constexpr std::size_t ss_wholesale_cost = 11;
    constexpr std::size_t ss_list_price = 12;
    constexpr std::size_t ss_sales_price = 13;
    constexpr std::size_t ss_ext_discount_amt = 14;
    constexpr std::size_t ss_ext_sales_price = 15;
    constexpr std::size_t ss_ext_wholesale_cost = 16;
    constexpr std::size_t ss_ext_list_price = 17;
    constexpr std::size_t ss_ext_tax = 18;
    constexpr std::size_t ss_coupon_amt = 19;
    constexpr std::size_t ss_net_paid = 20;
    constexpr std::size_t ss_net_paid_inc_tax = 21;
    constexpr std::size_t ss_net_profit = 22;
}

// time_dim (10 columns)
namespace time_dim {
    constexpr std::size_t t_time_sk = 0;
    constexpr std::size_t t_time_id = 1;
    constexpr std::size_t t_time = 2;
    constexpr std::size_t t_hour = 3;
    constexpr std::size_t t_minute = 4;
    constexpr std::size_t t_second = 5;
    constexpr std::size_t t_am_pm = 6;
    constexpr std::size_t t_shift = 7;
    constexpr std::size_t t_sub_shift = 8;
    constexpr std::size_t t_meal_time = 9;
}

// warehouse (14 columns)
namespace warehouse {
    constexpr std::size_t w_warehouse_sk = 0;
    constexpr std::size_t w_warehouse_id = 1;
    constexpr std::size_t w_warehouse_name = 2;
    constexpr std::size_t w_warehouse_sq_ft = 3;
    constexpr std::size_t w_street_number = 4;
    constexpr std::size_t w_street_name = 5;
    constexpr std::size_t w_street_type = 6;
    constexpr std::size_t w_suite_number = 7;
    constexpr std::size_t w_city = 8;
    constexpr std::size_t w_county = 9;
    constexpr std::size_t w_state = 10;
    constexpr std::size_t w_zip = 11;
    constexpr std::size_t w_country = 12;
    constexpr std::size_t w_gmt_offset = 13;
}

// web_page (14 columns)
namespace web_page {
    constexpr std::size_t wp_web_page_sk = 0;
    constexpr std::size_t wp_web_page_id = 1;
    constexpr std::size_t wp_rec_start_date_sk = 2;
    constexpr std::size_t wp_rec_end_date_sk = 3;
    constexpr std::size_t wp_creation_date_sk = 4;
    constexpr std::size_t wp_access_date_sk = 5;
    constexpr std::size_t wp_autogen_flag = 6;
    constexpr std::size_t wp_customer_sk = 7;
    constexpr std::size_t wp_url = 8;
    constexpr std::size_t wp_type = 9;
    constexpr std::size_t wp_char_count = 10;
    constexpr std::size_t wp_link_count = 11;
    constexpr std::size_t wp_image_count = 12;
    constexpr std::size_t wp_max_ad_count = 13;
}

// web_returns (24 columns)
namespace web_returns {
    constexpr std::size_t wr_returned_date_sk = 0;
    constexpr std::size_t wr_returned_time_sk = 1;
    constexpr std::size_t wr_item_sk = 2;
    constexpr std::size_t wr_refunded_customer_sk = 3;
    constexpr std::size_t wr_refunded_cdemo_sk = 4;
    constexpr std::size_t wr_refunded_hdemo_sk = 5;
    constexpr std::size_t wr_refunded_addr_sk = 6;
    constexpr std::size_t wr_returning_customer_sk = 7;
    constexpr std::size_t wr_returning_cdemo_sk = 8;
    constexpr std::size_t wr_returning_hdemo_sk = 9;
    constexpr std::size_t wr_returning_addr_sk = 10;
    constexpr std::size_t wr_web_page_sk = 11;
    constexpr std::size_t wr_reason_sk = 12;
    constexpr std::size_t wr_order_number = 13;
    constexpr std::size_t wr_quantity = 14;
    constexpr std::size_t wr_net_paid = 15;
    constexpr std::size_t wr_ext_tax = 16;
    constexpr std::size_t wr_net_paid_inc_tax = 17;
    constexpr std::size_t wr_fee = 18;
    constexpr std::size_t wr_ext_ship_cost = 19;
    constexpr std::size_t wr_refunded_cash = 20;
    constexpr std::size_t wr_reversed_charge = 21;
    constexpr std::size_t wr_store_credit = 22;
    constexpr std::size_t wr_net_loss = 23;
}

// web_sales (34 columns)
namespace web_sales {
    constexpr std::size_t ws_sold_date_sk = 0;
    constexpr std::size_t ws_sold_time_sk = 1;
    constexpr std::size_t ws_ship_date_sk = 2;
    constexpr std::size_t ws_item_sk = 3;
    constexpr std::size_t ws_bill_customer_sk = 4;
    constexpr std::size_t ws_bill_cdemo_sk = 5;
    constexpr std::size_t ws_bill_hdemo_sk = 6;
    constexpr std::size_t ws_bill_addr_sk = 7;
    constexpr std::size_t ws_ship_customer_sk = 8;
    constexpr std::size_t ws_ship_cdemo_sk = 9;
    constexpr std::size_t ws_ship_hdemo_sk = 10;
    constexpr std::size_t ws_ship_addr_sk = 11;
    constexpr std::size_t ws_web_page_sk = 12;
    constexpr std::size_t ws_web_site_sk = 13;
    constexpr std::size_t ws_ship_mode_sk = 14;
    constexpr std::size_t ws_warehouse_sk = 15;
    constexpr std::size_t ws_promo_sk = 16;
    constexpr std::size_t ws_order_number = 17;
    constexpr std::size_t ws_quantity = 18;
    constexpr std::size_t ws_wholesale_cost = 19;
    constexpr std::size_t ws_list_price = 20;
    constexpr std::size_t ws_sales_price = 21;
    constexpr std::size_t ws_ext_discount_amt = 22;
    constexpr std::size_t ws_ext_sales_price = 23;
    constexpr std::size_t ws_ext_wholesale_cost = 24;
    constexpr std::size_t ws_ext_list_price = 25;
    constexpr std::size_t ws_ext_tax = 26;
    constexpr std::size_t ws_coupon_amt = 27;
    constexpr std::size_t ws_ext_ship_cost = 28;
    constexpr std::size_t ws_net_paid = 29;
    constexpr std::size_t ws_net_paid_inc_tax = 30;
    constexpr std::size_t ws_net_paid_inc_ship = 31;
    constexpr std::size_t ws_net_paid_inc_ship_tax = 32;
    constexpr std::size_t ws_net_profit = 33;
}

// web_site (26 columns)
namespace web_site {
    constexpr std::size_t web_site_sk = 0;
    constexpr std::size_t web_site_id = 1;
    constexpr std::size_t web_rec_start_date_sk = 2;
    constexpr std::size_t web_rec_end_date_sk = 3;
    constexpr std::size_t web_name = 4;
    constexpr std::size_t web_open_date_sk = 5;
    constexpr std::size_t web_close_date_sk = 6;
    constexpr std::size_t web_class = 7;
    constexpr std::size_t web_manager = 8;
    constexpr std::size_t web_mkt_id = 9;
    constexpr std::size_t web_mkt_class = 10;
    constexpr std::size_t web_mkt_desc = 11;
    constexpr std::size_t web_market_manager = 12;
    constexpr std::size_t web_company_id = 13;
    constexpr std::size_t web_company_name = 14;
    constexpr std::size_t web_street_number = 15;
    constexpr std::size_t web_street_name = 16;
    constexpr std::size_t web_street_type = 17;
    constexpr std::size_t web_suite_number = 18;
    constexpr std::size_t web_city = 19;
    constexpr std::size_t web_county = 20;
    constexpr std::size_t web_state = 21;
    constexpr std::size_t web_zip = 22;
    constexpr std::size_t web_country = 23;
    constexpr std::size_t web_gmt_offset = 24;
    constexpr std::size_t web_tax_percentage = 25;
}

}  // namespace col
}  // namespace tpcds
