#!/usr/bin/env python3
"""
Generate include/tpch/dsdgen_col_idx.hpp — constexpr column indices per table.
Then rewrite dsdgen_converter.cpp to use col::NAME instead of builders[N].
Also fix append_addr_fields callers to use named base constants.
"""

import re, sys

WRAPPER   = "/home/tsafin/src/tpch-cpp/src/dsdgen/dsdgen_wrapper.cpp"
CONVERTER = "/home/tsafin/src/tpch-cpp/src/dsdgen/dsdgen_converter.cpp"
HEADER    = "/home/tsafin/src/tpch-cpp/include/tpch/dsdgen_col_idx.hpp"

# ---------------------------------------------------------------------------
# 1. Parse schemas from dsdgen_wrapper.cpp
# ---------------------------------------------------------------------------
wrapper = open(WRAPPER).read()

enum_to_table = {}
for m in re.finditer(r'case\s+TableType::(\w+):\s*return\s*"([^"]+)"', wrapper):
    enum_to_table[m.group(1)] = m.group(2)

case_pat = re.compile(
    r'case\s+TableType::(\w+):\s*\n\s*return\s+arrow::schema\(\{(.*?)\}\);', re.DOTALL)
field_pat = re.compile(r'arrow::field\(\s*"([^"]+)"')

table_columns = {}
for m in case_pat.finditer(wrapper):
    enum_name = m.group(1)
    if enum_name not in enum_to_table:
        continue
    tname = enum_to_table[enum_name]
    table_columns[tname] = field_pat.findall(m.group(2))

# ---------------------------------------------------------------------------
# 2. Generate dsdgen_col_idx.hpp
# ---------------------------------------------------------------------------
lines = [
    "// AUTO-GENERATED by scripts/gen_col_indices.py — DO NOT EDIT MANUALLY",
    "// Source of truth: src/dsdgen/dsdgen_wrapper.cpp (get_schema() switch)",
    "//",
    "// Provides zero-overhead named column indices for BuilderMap (vector) access.",
    "// Usage: builders[col::store_returns::sr_returned_date_sk]",
    "#pragma once",
    "#include <cstddef>",
    "",
    "namespace tpcds {",
    "namespace col {",
]

for tname in sorted(table_columns):
    cols = table_columns[tname]
    lines.append("")
    lines.append(f"// {tname} ({len(cols)} columns)")
    lines.append(f"namespace {tname} {{")
    for i, col in enumerate(cols):
        lines.append(f"    constexpr std::size_t {col} = {i};")
    lines.append("}")

lines += ["", "}  // namespace col", "}  // namespace tpcds", ""]

open(HEADER, 'w').write('\n'.join(lines))
print(f"Wrote {HEADER}  ({len(table_columns)} tables)")

# ---------------------------------------------------------------------------
# 3. Rewrite dsdgen_converter.cpp: builders[N] → builders[col::TABLE::NAME]
#    using the same find_func_end approach as before.
# ---------------------------------------------------------------------------
conv = open(CONVERTER).read()

# Build reverse map: for each table, index→col_name
table_index_to_col = {t: {i: c for i, c in enumerate(cols)}
                      for t, cols in table_columns.items()}

# Locate functions
func_pat = re.compile(
    r'(void\s+append_(\w+)_to_builders\s*\([^)]*\)\s*\{)', re.DOTALL)

def find_func_end(src, pos):
    depth = 1
    i = pos
    while i < len(src):
        if src[i] == '{':
            depth += 1
        elif src[i] == '}':
            depth -= 1
            if depth == 0:
                return i + 1
        i += 1
    return len(src)

func_positions = [(m.start(), m.group(2), m.end()) for m in func_pat.finditer(conv)]

idx_pat = re.compile(r'\bbuilders\[(\d+)\]')

new_conv = conv
offset = 0

for start, raw_table, body_start in func_positions:
    if raw_table not in table_index_to_col:
        continue
    idx_map = table_index_to_col[raw_table]

    adj_start = start + offset
    adj_body  = body_start + offset
    adj_end   = find_func_end(new_conv, adj_body)
    func_body = new_conv[adj_start:adj_end]

    def replace_idx(m, idx_map=idx_map, tname=raw_table):
        n = int(m.group(1))
        if n in idx_map:
            return f"builders[col::{tname}::{idx_map[n]}]"
        return m.group(0)  # leave unchanged (e.g. addr base+N offsets)

    new_body = idx_pat.sub(replace_idx, func_body)
    if new_body != func_body:
        new_conv = new_conv[:adj_start] + new_body + new_conv[adj_end:]
        offset += len(new_body) - len(func_body)

# Fix append_addr_fields: base+N offsets (0..9) inside the function body itself
# Those are NOT in an append_ function, so the loop above skipped them.
# Replace builders[base + N] patterns — these are fine as-is (readable with named base).
# Also fix the append_addr_fields callers: col::TABLE::street_number as the base arg.
addr_callers = {
    'append_addr_fields(r->cc_address, 20, builders)':
        'append_addr_fields(r->cc_address, col::call_center::cc_street_number, builders)',
    'append_addr_fields(r->web_address, 15, builders)':
        'append_addr_fields(r->web_address, col::web_site::web_street_number, builders)',
    'append_addr_fields(r->w_address, 4, builders)':
        'append_addr_fields(r->w_address, col::warehouse::w_street_number, builders)',
    'append_addr_fields(r->ca_address, 2, builders)':
        'append_addr_fields(r->ca_address, col::customer_address::ca_street_number, builders)',
    'append_addr_fields(r->address, 18, builders)':
        'append_addr_fields(r->address, col::store::s_street_number, builders)',
}
for old, new in addr_callers.items():
    new_conv = new_conv.replace(old, new)

# Add include of the new header near the top of dsdgen_converter.cpp
if '#include "tpch/dsdgen_col_idx.hpp"' not in new_conv:
    new_conv = new_conv.replace(
        '#include "tpch/dsdgen_converter.hpp"',
        '#include "tpch/dsdgen_converter.hpp"\n#include "tpch/dsdgen_col_idx.hpp"'
    )

# Count remaining numeric indices (should be only base+N inside append_addr_fields)
remaining = idx_pat.findall(new_conv)
named_count = new_conv.count('col::')
print(f"Named references inserted: {named_count}")
print(f"Remaining numeric indices (expected: base+0..9 in append_addr_fields): {len(remaining)}")

open(CONVERTER, 'w').write(new_conv)
print(f"Wrote {CONVERTER}")
